name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release/test
      - release/beta
      - release/live
      - release/debug

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  VERSION_SUFFIX: ${{ case(github.ref_name == 'release/live', '' ,github.ref_name == 'release/beta', '-beta', github.ref_name == 'release/debug', '-debug', '-test') }}

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # Intel based Mac
            args: '--target x86_64-apple-darwin'
            output_arch: 'X64'
          - platform: 'macos-latest' # Arm based Mac (M1 and above)
            args: '--target aarch64-apple-darwin'
          - platform: 'ubuntu-22.04' # Linux
            args: ''
          - platform: 'ubuntu-22.04-arm' # Arm based Linux
            args: ''
          - platform: 'windows-latest' # Windows 10/11
            args: ''
          - platform: 'windows-11-arm' # Arm based Windows 11
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev xdg-utils patchelf

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm' # Set this to npm, yarn or pnpm.

      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          # These targets are only used on macOS runners so it's in an `if` to slightly speed up Windows and Linux builds.
          targets: ${{ case(runner.os == 'macOS', 'aarch64-apple-darwin,x86_64-apple-darwin', '') }}

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: NPM Install Frontend Dependencies
        run: npm install

      - name: Tauri Info
        run: npm run tauri info

      - name: Build Binaries
        id: tauri-build
        uses: tauri-apps/tauri-action@v0
        env:
          # the action replaces \_\_VERSION\_\_ with the app version.
          APP_VERSION_FULL: __VERSION__${{ env.VERSION_SUFFIX }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_SUFFIX: ${{ format('{0}-{1}', runner.os, matrix.output_arch || runner.arch) }}
        with:
          tagName: 'v${{ env.APP_VERSION_FULL }}'
          releaseName: 'Slime2 v${{ env.APP_VERSION_FULL }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: ${{ github.ref_name != 'release/live' }}
          includeRelease: ${{ github.ref_name != 'release/debug' }}
          includeDebug: ${{ github.ref_name == 'release/debug' }}
          args: ${{ matrix.args }}
          assetNamePattern: 'Slime2-v[version]${{ env.VERSION_SUFFIX }}_${{ env.FILE_SUFFIX }}[ext]'

    outputs:
      app_version: ${{ steps.tauri-build.outputs.appVersion }}
      release_id: ${{ steps.tauri-build.outputs.releaseId }}
      arch_linux_file_name: 'Slime2-v${{ steps.tauri-build.outputs.appVersion }}${{ env.VERSION_SUFFIX }}_Arch-Linux.zip'

  publish-pkgbuild:
    permissions:
      contents: write
    needs: publish-tauri
    env:
      APP_VERSION: ${{ needs.publish-tauri.outputs.app_version }}
      RELEASE_ID: ${{ needs.publish-tauri.outputs.release_id }}
      FILE_NAME: ${{ needs.publish-tauri.outputs.arch_linux_file_name }}

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Update PKGBUILD
        uses: heyhusen/archlinux-package-action@v3.0.1
        with:
          path: pkgbuild
          pkgver: ${{ env.APP_VERSION }}
          pkgrel: 1
          updpkgsums: true

      - name: Create Arch Linux ZIP
        uses: thedoctor0/zip-release@0.7.6
        with:
          path: pkgbuild
          type: 'zip'
          filename: ${{ env.FILE_NAME }}
          custom: '--junk-paths'

      - name: Upload ZIP to Release
        uses: svenstaro/upload-release-action@v2
        with:
          release_id: ${{ env.RELEASE_ID }}
          file: ${{ env.FILE_NAME }}
          draft: true
