name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release/test
      - release/beta
      - release/live

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # Intel based Mac
            args: '--target x86_64-apple-darwin'
          - platform: 'macos-latest' # Arm based Mac (M1 and above)
            args: '--target aarch64-apple-darwin'
          - platform: 'ubuntu-22.04' # Linux
            args: ''
          - platform: 'ubuntu-22.04-arm' # Arm based Linux
            args: ''
          - platform: 'windows-latest' # Windows 10/11
            args: ''
          - platform: 'windows-11-arm' # Arm based Windows 11
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev xdg-utils patchelf

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm' # Set this to npm, yarn or pnpm.

      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          # These targets are only used on macOS runners so it's in an `if` to slightly speed up Windows and Linux builds.
          targets: ${{ case(runner.os == 'macOS', 'aarch64-apple-darwin,x86_64-apple-darwin', '') }}

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: NPM Install Frontend Dependencies
        run: npm install

      - name: Tauri Info
        run: npm run tauri info

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # the action replaces \_\_VERSION\_\_ with the app version.
          SLIME2_APP_VERSION: v__VERSION__${{ case(github.ref_name == 'release/live', '', github.ref_name == 'release/beta', '-beta', format('-test-{0}', github.sha)) }}

          SLIME2_FILE_SUFFIX: ${{ case(github.ref_name == 'release/live', '' ,github.ref_name == 'release/beta', '-beta', '-test') }}_${{ format('{0}-{1}', runner.os, runner.arch) }}
        with:
          tagName: '${{ env.SLIME2_APP_VERSION}}'
          releaseName: 'Slime2 ${{ env.SLIME2_APP_VERSION }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: ${{ github.ref_name != 'release/live' }}
          args: ${{ matrix.args }}
          assetNamePattern: 'slime2-v[version]${{ env.SLIME2_FILE_SUFFIX }}[ext]'
